on: [push, pull_request]
jobs:
  linux-gcc:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: update
      run:  sudo apt-get update
    - name: configure
      env:
        CC: gcc
        CXX: g++
      run: sudo apt-get install libprotobuf-dev protobuf-compiler libopencv-dev flatbuffers-compiler flatbuffers-compiler-dev
    - name: build
      run: | 
        git submodule update --init
        ls 3rdparty/flatbuffers/CMake/FindFlatBuffers.cmake
        mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build build -j 2
